### ISSUE TITLE
Broken link from README.md to API documentation

### ISSUE THREAD

**Issue by jfialli** [oracle/coherence-js-client#40]
**Describe the bug**
The README.md reachable from this URL has broken link to API doc.
(https://github.com/oracle/coherence-js-client)

**To Reproduce**
Steps to reproduce the behaviour:

From this link:
https://github.com/oracle/coherence-js-client

Scroll to bottom of page to References section and click the API link:

**References**

Oracle Coherence JavaScript Client - https://oracle.github.io/coherence/20.12/api/js/index.html

**Expected behaviour**

Uncertain if forgot to generate the API doc for 20.12 or if the link should have remained the original link.

https://coherence.community/20.06/api/js/index.html

**Comment by jfialli** [comment]
Did not mention that the link below  works and was provided as a workaround.


https://coherence.community/20.06/api/js/index.html

**Comment by rlubke** [comment]
Change applied.
